shape:
  favorite: '${favorite:}' # use blank as fallback value
  types:
    - 'Square'
    - 'Oval'
    - 'Triangle'
    - 'Circle'
    - 'Trapezoid'

---
spring:
  config:
    activate:
      on-cloud-platform: cloud_foundry
shape:
  favorite: '${vcap.services.shape.favorite:}'
